<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>9.0</LangVersion>
        <OutputType>Library</OutputType>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <RootNamespace>Core.Utils</RootNamespace>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

</Project>